### PR TITLE
Missing dependency @babel/runtime 

### LINKED ISSUE #2221: NodeJS Web3 1.0.0-beta.38 and 1.0.0-beta.39: Cannot find module '@babel/runtime/helpers/classCallCheck'
Hi!

Web3 1.0.0-beta.37 did work fine with all my systems. But now, after upgrading to 1.0.0-beta.38 it stopped working. Even after a clean install into a new empty folder, it doesn't work on my Mac, also tried Ubuntu 14.04 LTS with same results. As you can see from the output below, it really is a system-agnostic bug related to the `require()` + npm module directory resolver, so, most likely, a problem somewhere in the web3.js codebase itself.

```shell
+ web3@1.0.0-beta.38
added 298 packages from 205 contributors in 38.338s
[+] no known vulnerabilities found [15378 packages audited]
```

```JavaScript
> const Web3 = require('web3')
Error: Cannot find module '@babel/runtime/helpers/classCallCheck'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
>
```

```shell
$ uname -a
Darwin mbp.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
$ node --version
v9.2.0
$ npm --version
6.0.0
```

Questions:

- Why is that `babel` stuff missing after a clean install?
- What would be a proper workaround for this issue?

### PR DESCRIPTION
**Pull request by nivida**
## Description

Fixes #2221 

## Type of change

- [x] Bug fix 

## Checklist:

- [x] I have selected the correct base branch.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no warnings.
- [x] I have updated or added types for all modules I've changed
- [x] Any dependent changes have been merged and published in downstream modules.
- [x] I ran ```npm run test``` in the root folder with success and extended the tests if necessary.
- [x] I ran ```npm run build``` in the root folder and tested it in the browser and with node.
- [x] I ran ```npm run dtslint``` in the root folder and tested that all my types are correct
- [ ] I have tested my code on the live network.

### CODE REVIEW

**Comment by AScripnic** [comment]
Hello @nivida, can you tell please when this will be deployed?

**Comment by nivida** [comment]
@AScripnic I've planned to fix bugs and improve the documentation today. All these changes will be released this [night](https://greenwichmeantime.com/time-zone/europe/european-union/germany/berlin/time/).
