### ISSUE TITLE
node 10 alpine - Error with scrypt

### ISSUE THREAD

**Issue by sulliwane** [ethereum/web3.js#1662]
Dockerfile:
```
FROM node:10.2-alpine

RUN mkdir -p /app
WORKDIR /app

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh python2 python2-dev py-setuptools dumb-init musl linux-headers build-base ca-certificates

COPY package.json package.json
RUN npm install

COPY . .

CMD ["npm", "start"]
```

it fails with error:
```
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
In file included from ../../nan/nan.h:51:0,
                 from ../src/node-boilerplate/scrypt_common.cc:28:
/root/.node-gyp/10.2.0/include/node/node.h:53:50: fatal error: core.h: No such file or directory
 #include "core.h"  // NOLINT(build/include_order)
                                                  ^
compilation terminated.
make: *** [scrypt.target.mk:115: Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o] Error 1
make: Leaving directory '/app/node_modules/scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.15.0-20-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/scrypt
gyp ERR! node -v v10.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-25T16_50_24_500Z-debug.log
```

But It works with node alpine v10.1!

**Comment by Levino** [comment]
I think it suffices to open this issue once at at the right place. https://github.com/ethereum/web3.js/issues/1662 Can be closed here.
