### ISSUE TITLE
TypeError: XMLHttpRequest is not a function

### ISSUE THREAD

**Issue by Viking-yu** [ethereum/web3.js#579]
When I upgraded Meteor from V1.4.1 to V1.4.3.2, an issue TypeError: XMLHttpRequest is not a function occured when web3 initialized. 
```
=> Started proxy.                             
=> Started MongoDB.                           
W20170320-16:50:21.758(8)? (STDERR) /Users/viking/.meteor/packages/meteor-tool/.1.4.3_2.1hyysv9++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170320-16:50:21.838(8)? (STDERR) 						throw(ex);
W20170320-16:50:21.839(8)? (STDERR) 						^
W20170320-16:50:21.839(8)? (STDERR) 
W20170320-16:50:21.840(8)? (STDERR) TypeError: XMLHttpRequest is not a function
W20170320-16:50:21.840(8)? (STDERR)     at [object Object].HttpProvider.prepareRequest (packages/ethereum_web3.js:4259:17)
W20170320-16:50:21.841(8)? (STDERR)     at [object Object].HttpProvider.send (packages/ethereum_web3.js:4275:24)
W20170320-16:50:21.841(8)? (STDERR)     at [object Object].RequestManager.send (packages/ethereum_web3.js:6206:32)
W20170320-16:50:21.842(8)? (STDERR)     at Eth.get [as blockNumber] (packages/ethereum_web3.js:6109:62)
W20170320-16:50:21.843(8)? (STDERR)     at meteorInstall.server.events.js (server/events.js:36:57)
W20170320-16:50:21.843(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170320-16:50:21.844(8)? (STDERR)     at require (packages/modules-runtime.js:120:16)
```

Here is my packages.json of the project:
```
{
  "name": "MyProject",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "meteor-node-stubs": "~0.2.0",
    "xhr2": "^0.1.4",
    "bcrypt": "^1.0.1",
    "clipboard": "^1.5.12",
    "babel-runtime": "^6.18.0"
  }
}
```

I'm using 'meteor/ethereum:web3' package. I've tried the following respectively: `meteor npm install --save xhr2`, `meteor npm install --save xmlhttprequest`, and added the following to refer the XMLHttpRequest:
```
var XMLHttpRequest = require('xhr2').XMLHttpRequest;
var xhr = new XMLHttpRequest();

import { Web3 } from 'meteor/ethereum:web3';
```

But none worked. 

Any suggestion?

**Comment by peculiarity** [comment]
As far as I see in their documentation - [xhr2](https://github.com/pwnall/node-xhr2) , the `require('xhr2')` returns the XMLHttpRequest. You don't have to access it like you are doing.

**Comment by Joeblockmark** [comment]
@yuwiggin Did you manage to fix this?

**Comment by Davidyuk** [comment]
Instead `ethereum:web3` Meteor package I have used `web3@0.20.1` NPM package, and it works ok with Meteor version 1.5.1.
Firstly I have tried `1.0.0-beta.15` version, but it fails with syntax error:
```
W20170806-02:27:20.135(10)? (STDERR) /.../node_modules/web3/packages/web3-eth-accounts/node_modules/eth-lib/src/account.js:6
W20170806-02:27:20.189(10)? (STDERR) const {keccak256, keccak256s} = require("./hash");
W20170806-02:27:20.190(10)? (STDERR)       ^
W20170806-02:27:20.191(10)? (STDERR) 
W20170806-02:27:20.192(10)? (STDERR) SyntaxError: Unexpected token {
```

**Comment by alexpriceonline** [comment]
I'm still fighting with this issue... Any idea what's going on?

**Comment by sousacanfly** [comment]
I'm having the same issue with a light geth node

**Comment by nicoszerman** [comment]
+1

**Comment by nivida** [comment]
Have you tried it with the ```web3@0.20.x``` from NPM as mentioned above from davidyuk? 
@sousacanfly @nicszerman @alexpriceonline

**Comment by tanutapi** [comment]
Using npm's web3@0.20.7 seems OK for me.

I am able to do
```
const web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:8545'));
console.log(web3.eth.accounts);
```
in server code. My geth are running in "light" mode.

**Comment by nivida** [comment]
I've closed this issue because it seems to work with 0.20. If this error still occurs in the 1.0 version then please drop a comment here and tag me.

**Comment by ezekelechig** [comment]
Hello I am getting this issue:

TypeError: 'XMLHttpRequest' is not a function

![image](https://user-images.githubusercontent.com/16583668/55691807-9f434400-5967-11e9-9db6-ebddea178e06.png)
<img width="394" alt="Screen Shot 2019-04-07 at 7 01 13 PM" src="https://user-images.githubusercontent.com/16583668/55691829-c1d55d00-5967-11e9-93ac-30c4368dc3e0.png">

**Comment by ezekelechig** [comment]
Hello I am getting this issue @nivida 

![image](https://user-images.githubusercontent.com/16583668/55691837-e7fafd00-5967-11e9-81fd-ee715e194bd2.png)
