### ISSUE TITLE
1.0.0-beta.46 subscribe events without callback throw exception: `TypeError: callback is not a function`

### ISSUE THREAD

**Issue by BigMurry** [ethereum/web3.js#2364]
#### Expected behavior
`contractsInstance.events.MyEvent.on('data', evt => {})` should work.
#### Actual behavior
throw exception: 
```
TypeError: callback is not a function
    at web3-core-subscriptions.umd.js:110
    at Array.forEach (<anonymous>)
    at web3-core-subscriptions.umd.js:108
```
#### Steps to reproduce the behavior
same code works in `1.0.0-beta.36`
```javascript
const Web3 = require('web3');
const abi = [...];
const addr = '0x....';
const web3 = new Web3(window.web3.currentProvider);
const contractInstance = new web3.eth.Contract(abi, addr);
contractInstance.events.MyEvent({filter, fromBlock}) // no callback here
.on('data', evt => {
  console.log(evt);
})
.on('error', e => {
  console.log(e);
});
```
#### Error Logs
```
TypeError: callback is not a function
    at web3-core-subscriptions.umd.js:110
    at Array.forEach (<anonymous>)
    at web3-core-subscriptions.umd.js:108
```
#### The code snapshot:
<img width="816" alt="wechatimg167" src="https://user-images.githubusercontent.com/12495406/52530943-d8d14780-2d48-11e9-837a-4588e6ebf269.png">

#### Versions
Web3.js - `1.0.0-beta.46`
Nodejs - `v10.14.0`
NPM - `v6.4.1`

**Comment by nivida** [comment]
Thanks for creating this issue! I've just fixed it in PR https://github.com/ethereum/web3.js/pull/2366
